// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package Entity

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"project/Technical_Service/ORM/Entity/EntityStruct"
)

func newStock(db *gorm.DB, opts ...gen.DOOption) stock {
	_stock := stock{}

	_stock.stockDo.UseDB(db, opts...)
	_stock.stockDo.UseModel(&EntityStruct.Stock{})

	tableName := _stock.stockDo.TableName()
	_stock.ALL = field.NewAsterisk(tableName)
	_stock.UserID = field.NewInt32(tableName, "user_id")
	_stock.StockShortName = field.NewString(tableName, "stock_short_name")
	_stock.StockID = field.NewInt32(tableName, "stock_id")
	_stock.UserUser = stockBelongsToUserUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("UserUser", "EntityStruct.User"),
	}

	_stock.fillFieldMap()

	return _stock
}

type stock struct {
	stockDo

	ALL            field.Asterisk
	UserID         field.Int32
	StockShortName field.String
	StockID        field.Int32
	UserUser       stockBelongsToUserUser

	fieldMap map[string]field.Expr
}

func (s stock) Table(newTableName string) *stock {
	s.stockDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s stock) As(alias string) *stock {
	s.stockDo.DO = *(s.stockDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *stock) updateTableName(table string) *stock {
	s.ALL = field.NewAsterisk(table)
	s.UserID = field.NewInt32(table, "user_id")
	s.StockShortName = field.NewString(table, "stock_short_name")
	s.StockID = field.NewInt32(table, "stock_id")

	s.fillFieldMap()

	return s
}

func (s *stock) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *stock) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 4)
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["stock_short_name"] = s.StockShortName
	s.fieldMap["stock_id"] = s.StockID

}

func (s stock) clone(db *gorm.DB) stock {
	s.stockDo.ReplaceConnPool(db.Statement.ConnPool)
	s.UserUser.db = db.Session(&gorm.Session{Initialized: true})
	s.UserUser.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s stock) replaceDB(db *gorm.DB) stock {
	s.stockDo.ReplaceDB(db)
	s.UserUser.db = db.Session(&gorm.Session{})
	return s
}

type stockBelongsToUserUser struct {
	db *gorm.DB

	field.RelationField
}

func (a stockBelongsToUserUser) Where(conds ...field.Expr) *stockBelongsToUserUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a stockBelongsToUserUser) WithContext(ctx context.Context) *stockBelongsToUserUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a stockBelongsToUserUser) Session(session *gorm.Session) *stockBelongsToUserUser {
	a.db = a.db.Session(session)
	return &a
}

func (a stockBelongsToUserUser) Model(m *EntityStruct.Stock) *stockBelongsToUserUserTx {
	return &stockBelongsToUserUserTx{a.db.Model(m).Association(a.Name())}
}

func (a stockBelongsToUserUser) Unscoped() *stockBelongsToUserUser {
	a.db = a.db.Unscoped()
	return &a
}

type stockBelongsToUserUserTx struct{ tx *gorm.Association }

func (a stockBelongsToUserUserTx) Find() (result *EntityStruct.User, err error) {
	return result, a.tx.Find(&result)
}

func (a stockBelongsToUserUserTx) Append(values ...*EntityStruct.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a stockBelongsToUserUserTx) Replace(values ...*EntityStruct.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a stockBelongsToUserUserTx) Delete(values ...*EntityStruct.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a stockBelongsToUserUserTx) Clear() error {
	return a.tx.Clear()
}

func (a stockBelongsToUserUserTx) Count() int64 {
	return a.tx.Count()
}

func (a stockBelongsToUserUserTx) Unscoped() *stockBelongsToUserUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type stockDo struct{ gen.DO }

type IStockDo interface {
	gen.SubQuery
	Debug() IStockDo
	WithContext(ctx context.Context) IStockDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IStockDo
	WriteDB() IStockDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IStockDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IStockDo
	Not(conds ...gen.Condition) IStockDo
	Or(conds ...gen.Condition) IStockDo
	Select(conds ...field.Expr) IStockDo
	Where(conds ...gen.Condition) IStockDo
	Order(conds ...field.Expr) IStockDo
	Distinct(cols ...field.Expr) IStockDo
	Omit(cols ...field.Expr) IStockDo
	Join(table schema.Tabler, on ...field.Expr) IStockDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IStockDo
	RightJoin(table schema.Tabler, on ...field.Expr) IStockDo
	Group(cols ...field.Expr) IStockDo
	Having(conds ...gen.Condition) IStockDo
	Limit(limit int) IStockDo
	Offset(offset int) IStockDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IStockDo
	Unscoped() IStockDo
	Create(values ...*EntityStruct.Stock) error
	CreateInBatches(values []*EntityStruct.Stock, batchSize int) error
	Save(values ...*EntityStruct.Stock) error
	First() (*EntityStruct.Stock, error)
	Take() (*EntityStruct.Stock, error)
	Last() (*EntityStruct.Stock, error)
	Find() ([]*EntityStruct.Stock, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*EntityStruct.Stock, err error)
	FindInBatches(result *[]*EntityStruct.Stock, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*EntityStruct.Stock) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IStockDo
	Assign(attrs ...field.AssignExpr) IStockDo
	Joins(fields ...field.RelationField) IStockDo
	Preload(fields ...field.RelationField) IStockDo
	FirstOrInit() (*EntityStruct.Stock, error)
	FirstOrCreate() (*EntityStruct.Stock, error)
	FindByPage(offset int, limit int) (result []*EntityStruct.Stock, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IStockDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s stockDo) Debug() IStockDo {
	return s.withDO(s.DO.Debug())
}

func (s stockDo) WithContext(ctx context.Context) IStockDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s stockDo) ReadDB() IStockDo {
	return s.Clauses(dbresolver.Read)
}

func (s stockDo) WriteDB() IStockDo {
	return s.Clauses(dbresolver.Write)
}

func (s stockDo) Session(config *gorm.Session) IStockDo {
	return s.withDO(s.DO.Session(config))
}

func (s stockDo) Clauses(conds ...clause.Expression) IStockDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s stockDo) Returning(value interface{}, columns ...string) IStockDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s stockDo) Not(conds ...gen.Condition) IStockDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s stockDo) Or(conds ...gen.Condition) IStockDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s stockDo) Select(conds ...field.Expr) IStockDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s stockDo) Where(conds ...gen.Condition) IStockDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s stockDo) Order(conds ...field.Expr) IStockDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s stockDo) Distinct(cols ...field.Expr) IStockDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s stockDo) Omit(cols ...field.Expr) IStockDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s stockDo) Join(table schema.Tabler, on ...field.Expr) IStockDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s stockDo) LeftJoin(table schema.Tabler, on ...field.Expr) IStockDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s stockDo) RightJoin(table schema.Tabler, on ...field.Expr) IStockDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s stockDo) Group(cols ...field.Expr) IStockDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s stockDo) Having(conds ...gen.Condition) IStockDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s stockDo) Limit(limit int) IStockDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s stockDo) Offset(offset int) IStockDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s stockDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IStockDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s stockDo) Unscoped() IStockDo {
	return s.withDO(s.DO.Unscoped())
}

func (s stockDo) Create(values ...*EntityStruct.Stock) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s stockDo) CreateInBatches(values []*EntityStruct.Stock, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s stockDo) Save(values ...*EntityStruct.Stock) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s stockDo) First() (*EntityStruct.Stock, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*EntityStruct.Stock), nil
	}
}

func (s stockDo) Take() (*EntityStruct.Stock, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*EntityStruct.Stock), nil
	}
}

func (s stockDo) Last() (*EntityStruct.Stock, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*EntityStruct.Stock), nil
	}
}

func (s stockDo) Find() ([]*EntityStruct.Stock, error) {
	result, err := s.DO.Find()
	return result.([]*EntityStruct.Stock), err
}

func (s stockDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*EntityStruct.Stock, err error) {
	buf := make([]*EntityStruct.Stock, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s stockDo) FindInBatches(result *[]*EntityStruct.Stock, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s stockDo) Attrs(attrs ...field.AssignExpr) IStockDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s stockDo) Assign(attrs ...field.AssignExpr) IStockDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s stockDo) Joins(fields ...field.RelationField) IStockDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s stockDo) Preload(fields ...field.RelationField) IStockDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s stockDo) FirstOrInit() (*EntityStruct.Stock, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*EntityStruct.Stock), nil
	}
}

func (s stockDo) FirstOrCreate() (*EntityStruct.Stock, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*EntityStruct.Stock), nil
	}
}

func (s stockDo) FindByPage(offset int, limit int) (result []*EntityStruct.Stock, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s stockDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s stockDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s stockDo) Delete(models ...*EntityStruct.Stock) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *stockDo) withDO(do gen.Dao) *stockDo {
	s.DO = *do.(*gen.DO)
	return s
}
