// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package EntityStruct

const TableNameStock = "Stock"

// Stock mapped from table <stock>
type Stock struct {
	UserID         *int32  `gorm:"column:user_id" json:"userId"`
	StockShortName *string `gorm:"column:stock_short_name" json:"stockShortName"`
	StockID        int32   `gorm:"column:stock_id;primaryKey;autoIncrement:true" json:"stockId" validate:""`
	User           *User   `gorm:"foreignKey:user_id;references:user_id" json:"user"`
}

// TableName Stock's table name
func (*Stock) TableName() string {
	return TableNameStock
}
