// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package EntityStruct

const TableNameUser = "User"

// User mapped from table <User>
type User struct {
	UserID   int32    `gorm:"column:user_id;primaryKey;autoIncrement:true" json:"userId" validate:""`
	Username *string  `gorm:"column:username" json:"username"`
	Password *string  `gorm:"column:password" json:"password"`
	Stock    []*Stock `gorm:"foreignKey:user_id;references:user_id" json:"stock"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
