// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package EntityStruct

const TableNameUser = "User"

// User mapped from table <User>
type User struct {
	UserID   int32    `gorm:"column:user_id;primaryKey;autoIncrement:true" json:"userId" validate:""`
	Username string   `gorm:"column:username;not null" json:"username" validate:"required"`
	Password string   `gorm:"column:password;not null" json:"password" validate:"required"`
	Email    string   `gorm:"column:email;not null" json:"email" validate:"required"`
	Stock    []*Stock `gorm:"foreignKey:user_id;references:user_id" json:"stock"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
